apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-pod-sweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: pod-sweeper
  template:
    metadata:
      labels:
        airbyte: pod-sweeper
    spec:
      serviceAccountName: airbyte-admin
      containers:
        - name: airbyte-pod-sweeper
          # resources:
          #   limits:
          #     cpu: 0.5
          #     memory: 128Mi
          image: bitnami/kubectl
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /script/sweep-pod.sh
              subPath: sweep-pod.sh
              name: sweep-pod-script
          command: ["/bin/bash", "-c", /script/sweep-pod.sh]
      volumes:
        - name: sweep-pod-script
          configMap:
            name: sweep-pod-script
            defaultMode: 0755