apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-db
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: db
  template:
    metadata:
      labels:
        airbyte: db
    spec:
      containers:
        - name: airbyte-db-container
          # resources:
          #   limits:
          #     cpu: 2
          #     memory: 2Gi
          image: airbyte/db:0.35.30-alpha 
          env:
            - name: POSTGRES_DB
              value: db-airbyte
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_USER
              value: docker
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: airbyte-volume-db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: airbyte-volume-db
          persistentVolumeClaim:
            claimName: airbyte-volume-db