apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: temporal
  template:
    metadata:
      labels:
        airbyte: temporal
    spec:
      containers:
        - name: airbyte-temporal
          image: temporalio/auto-setup:1.7.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_PASSWORD
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "config/dynamicconfig/development.yaml"
            - name: DB
              value: "postgresql"
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_PORT
            - name: POSTGRES_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_HOST

          ports:
            - containerPort: 7233
          volumeMounts:
            - name: airbyte-temporal-dynamicconfig
              mountPath: "/etc/temporal/config/dynamicconfig/"
      volumes:
        - name: airbyte-temporal-dynamicconfig
          configMap:
            name: airbyte-temporal-dynamicconfig
            items:
              - key: development.yaml
                path: development.yaml
